### ISSUE TITLE
does this part mean QAT or PTQ?

### ISSUE THREAD

**Issue by cj401** [thb1314/mmyolo_tensorrt#1]
Hi,

I wonder if this line https://github.com/thb1314/mmyolo_tensorrt/blob/main/mmyolo/self_study_scripts/15qat_train_nvidia_trt.py#L48 means QAT or PTQ model? is it possible to provide a checkpoint file to play around?

Thanks

**Comment by thb1314** [comment]
a PTQ calibrated model used to provide pretrained model weight and model structure (use `torch.save`).

**Comment by cj401** [comment]
Hi @thb1314 , thanks for your prompt reply.

I wonder how a PTQ calibrated model is generated. I usually do PTQs based on onnx files for trained models with calibration data.  

If it is possible, can we chat offline for this issue? Thanks

**Comment by thb1314** [comment]
@cj401 PTQ model can also be calibrated using torch, see `save_calib_model` in https://github.com/thb1314/mmyolo_tensorrt/blob/main/mmyolo/self_study_scripts/14load_sensitive_analysis.py#L81
You can also write a email to me (haibintian@foxmail.com) with your question and you wechat account.

**Comment by cj401** [comment]
Hi @thb1314, thanks and sent emails to your foxmail already.
