### ISSUE TITLE
RuntimeError: The size of tensor a (8400) must match the size of tensor b (25200) at non-singleton dimension 1

### ISSUE THREAD

**Issue by jiangq195** [thb1314/mmyolo_tensorrt#2]

**Comment by jiangq195** [comment]
flatten_cls_scores = [
            cls_score.permute(0, 2, 3, 1).reshape(-1, int(cls_score.shape[3] * cls_score.shape[2] * cls_score.shape[1] // self.num_classes),
                                                  self.num_classes)
            for cls_score in cls_scores
        ]

**Comment by jiangq195** [comment]
flatten_bbox_preds = [
            bbox_pred.permute(0, 2, 3, 1).reshape(-1, int(bbox_pred.shape[1] * bbox_pred.shape[2] * bbox_pred.shape[3] // box_dim), box_dim)
            for bbox_pred in bbox_preds
        ]

**Comment by thb1314** [comment]
请详细描述你的问题
