### ISSUE TITLE
报错RuntimeError: The size of tensor a (8400) must match the size of tensor b (25200) at non-singleton dimension 1

### ISSUE THREAD

**Issue by NLPOR** [thb1314/mmyolo_tensorrt#4]
转换yolov5 yolov7 yolov8 的onnx模型报上述维度不一致的错误

![image](https://github.com/thb1314/mmyolo_tensorrt/assets/24563120/4c7eec78-bd46-4acf-b77c-ef6995eddeeb)

什么原因呢

**Comment by thb1314** [comment]
@NLPOR 可能是我改了一些配置项的原因，晚上定位后更新代码解决改bug

**Comment by jianke000** [comment]
我也遇到了上述的问题，不过每次跑代码时，出现的错误都不一样，例如：
![1 (10) - JupyterLab — Mozilla Firefox 2023_12_13 19_09_46](https://github.com/thb1314/mmyolo_tensorrt/assets/59756633/41464c3d-bb65-43f0-ba8d-fe85402ebfb3)
请问这种原因是为什么呢

**Comment by thb1314** [comment]
@NLPOR 不好意思啊，昨晚有些事情耽搁了，今天我一定看。
@jianke000 这个问题我也会看一下

**Comment by NLPOR** [comment]
![image](https://github.com/thb1314/mmyolo_tensorrt/assets/24563120/e58de364-764d-44ac-be02-d83fde83b587)
我定位了到代码维度不一致的地方强行reshap了这里，没有报错了，但是不熟悉整体代码，不是很知道具体原因，楼主解决后麻烦告知一下

**Comment by thb1314** [comment]
> ![image](https://private-user-images.githubusercontent.com/24563120/290376640-e58de364-764d-44ac-be02-d83fde83b587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjA1MTIsIm5iZiI6MTcwMjUyMDIxMiwicGF0aCI6Ii8yNDU2MzEyMC8yOTAzNzY2NDAtZTU4ZGUzNjQtNzY0ZC00NGFjLWJlMDItZDgzZmRlODNiNTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NDE0N2U3YmU5M2IzZDRjOTkzNWE5MjE2ODQ0ODMxYjM3YWYyMGVmZWQxMjhjODU2NzkzY2FkNmJjMTkyMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rmGShekWizuwc2tZ6A29p5mNfvlFzo4hvIsEvF4Oga0) 我定位了到代码维度不一致的地方强行reshap了这里，没有报错了，但是不熟悉整体代码，不是很知道具体原因，楼主解决后麻烦告知一下

@NLPOR 这么reshape会有一个问题，即不支持多batch了，可以考虑再优化下

**Comment by thb1314** [comment]
@NLPOR @jianke000 导出已修复，请查看

**Comment by thb1314** [comment]
@NLPOR 关于此问题如果还有疑问请重开issue即可
