### ISSUE TITLE
The size of tensor a (8400) must match the size of tensor b (537600) at non-singleton dimension 1

### ISSUE THREAD

**Issue by ioir123ju** [thb1314/mmyolo_tensorrt#6]
**environment**
Tensorrt 8.0.
**command**
`python self_study_scripts/11infer_tensorrt_dynamic_axes_mqbench_minmax.py ./data/coco/val2017/ $config_file ./work_dirs/$workdir/end2end.onnx $pth_path --max-batch-size=1 --calib-imgs=./data/coco/val2017 --enable-int8 --enable-fp16
`
![image](https://github.com/thb1314/mmyolo_tensorrt/assets/14951957/c07606f5-49e2-4a49-8b3c-6a3852750dc0)

**Comment by thb1314** [comment]
已修改，你再试试 @ioir123ju
