### ISSUE TITLE
如果导入tensorrt的int8后，如何在deepstream中使用？

### ISSUE THREAD

**Issue by tms2003** [thb1314/mmyolo_tensorrt#9]
一般我们使用的是https://github.com/marcoslucianops/DeepStream-Yolo 插件，它会自动做量化，但丢失精确严重。如何在本项目中导出可用呢？

**Comment by thb1314** [comment]
@tms2003 
这不属于本项目功能支持范围，如果需要模型加速相关付费咨询服务，欢迎给 `zhuilewang@163.com` 发邮件
